import {hash} from "starknet";

export const SELECTOR_KEYS ={
    StartGame: hash.getSelectorFromName("StartGame"),
    AdventurerUpgraded: hash.getSelectorFromName("AdventurerUpgraded"),
    DiscoveredHealth: hash.getSelectorFromName("DiscoveredHealth"),
    DiscoveredGold: hash.getSelectorFromName("DiscoveredGold"),
    DiscoveredXP: hash.getSelectorFromName("DiscoveredXP"),
    DodgedObstacle: hash.getSelectorFromName("DodgedObstacle"),
    HitByObstacle: hash.getSelectorFromName("HitByObstacle"),
    DiscoveredBeast: hash.getSelectorFromName("DiscoveredBeast"),
    AmbushedByBeast: hash.getSelectorFromName("AmbushedByBeast"),
    AttackedBeast: hash.getSelectorFromName("AttackedBeast"),
    AttackedByBeast: hash.getSelectorFromName("AttackedByBeast"),
    SlayedBeast: hash.getSelectorFromName("SlayedBeast"),
    FleeFailed: hash.getSelectorFromName("FleeFailed"),
    FleeSucceeded: hash.getSelectorFromName("FleeSucceeded"),
    PurchasedItems: hash.getSelectorFromName("PurchasedItems"),
    PurchasedPotions: hash.getSelectorFromName("PurchasedPotions"),
    EquippedItems: hash.getSelectorFromName("EquippedItems"),
    DroppedItems: hash.getSelectorFromName("DroppedItems"),
    GreatnessIncreased: hash.getSelectorFromName("GreatnessIncreased"),
    ItemsLeveledUp: hash.getSelectorFromName("ItemsLeveledUp"),
    NewHighScore: hash.getSelectorFromName("NewHighScore"),
    AdventurerDied: hash.getSelectorFromName("AdventurerDied"),
    AdventurerLeveledUp: hash.getSelectorFromName("AdventurerLeveledUp"),
    NewItemsAvailable: hash.getSelectorFromName("NewItemsAvailable"),
    IdleDeathPenalty: hash.getSelectorFromName("IdleDeathPenalty"),
    ResUpdate: hash.getSelectorFromName("ResUpdate"),
}


export const ITEMS = {
    1: "Pendant",
    2: "Necklace",
    3: "Amulet",
    4: "Silver Ring",
    5: "Bronze Ring",
    6: "Platinum Ring",
    7: "Titanium Ring",
    8: "Gold Ring",
    9: "Ghost Wand",
    10: "Grave Wand",
    11: "Bone Wand",
    12: "Wand",
    13: "Grimoire",
    14: "Chronicle",
    15: "Tome",
    16: "Book",
    17: "Divine Robe",
    18: "Silk Robe",
    19: "Linen Robe",
    20: "Robe",
    21: "Shirt",
    22: "Crown",
    23: "Divine Hood",
    24: "Silk Hood",
    25: "Linen Hood",
    26: "Hood",
    27: "Brightsilk Sash",
    28: "Silk Sash",
    29: "Wool Sash",
    30: "Linen Sash",
    31: "Sash",
    32: "Divine Slippers",
    33: "Silk Slippers",
    34: "Wool Shoes",
    35: "Linen Shoes",
    36: "Shoes",
    37: "Divine Gloves",
    38: "Silk Gloves",
    39: "Wool Gloves",
    40: "Linen Gloves",
    41: "Gloves",
    42: "Katana",
    43: "Falchion",
    44: "Scimitar",
    45: "Long Sword",
    46: "Short Sword",
    47: "Demon Husk",
    48: "Dragonskin Armor",
    49: "Studded Leather Armor",
    50: "Hard Leather Armor",
    51: "Leather Armor",
    52: "Demon Crown",
    53: "Dragons Crown",
    54: "War Cap",
    55: "Leather Cap",
    56: "Cap",
    57: "Demonhide Belt",
    58: "Dragonskin Belt",
    59: "Studded Leather Belt",
    60: "Hard Leather Belt",
    61: "Leather Belt",
    62: "Demonhide Boots",
    63: "Dragonskin Boots",
    64: "Studded Leather Boots",
    65: "Hard Leather Boots",
    66: "Leather Boots",
    67: "Demons Hands",
    68: "Dragonskin Gloves",
    69: "Studded Leather Gloves",
    70: "Hard Leather Gloves",
    71: "Leather Gloves",
    72: "Warhammer",
    73: "Quarterstaff",
    74: "Maul",
    75: "Mace",
    76: "Club",
    77: "Holy Chestplate",
    78: "Ornate Chestplate",
    79: "Plate Mail",
    80: "Chain Mail",
    81: "Ring Mail",
    82: "Ancient Helm",
    83: "Ornate Helm",
    84: "Great Helm",
    85: "Full Helm",
    86: "Helm",
    87: "Ornate Belt",
    88: "War Belt",
    89: "Plated Belt",
    90: "Mesh Belt",
    91: "Heavy Belt",
    92: "Holy Greaves",
    93: "Ornate Greaves",
    94: "Greaves",
    95: "Chain Boots",
    96: "Heavy Boots",
    97: "Holy Gauntlets",
    98: "Ornate Gauntlets",
    99: "Gauntlets",
    100: "Chain Gloves",
    101: "Heavy Gloves",
};

export const ITEM_TYPES = {
    1: "Necklace",
    2: "Necklace",
    3: "Necklace",
    4: "Ring",
    5: "Ring",
    6: "Ring",
    7: "Ring",
    8: "Ring",
    9: "Magic",
    10: "Magic",
    11: "Magic",
    12: "Magic",
    13: "Magic",
    14: "Magic",
    15: "Magic",
    16: "Magic",
    17: "Cloth",
    18: "Cloth",
    19: "Cloth",
    20: "Cloth",
    21: "Cloth",
    22: "Cloth",
    23: "Cloth",
    24: "Cloth",
    25: "Cloth",
    26: "Cloth",
    27: "Cloth",
    28: "Cloth",
    29: "Cloth",
    30: "Cloth",
    31: "Cloth",
    32: "Cloth",
    33: "Cloth",
    34: "Cloth",
    35: "Cloth",
    36: "Cloth",
    37: "Cloth",
    38: "Cloth",
    39: "Cloth",
    40: "Cloth",
    41: "Cloth",
    42: "Blade",
    43: "Blade",
    44: "Blade",
    45: "Blade",
    46: "Blade",
    47: "Hide",
    48: "Hide",
    49: "Hide",
    50: "Hide",
    51: "Hide",
    52: "Hide",
    53: "Hide",
    54: "Hide",
    55: "Hide",
    56: "Hide",
    57: "Hide",
    58: "Hide",
    59: "Hide",
    60: "Hide",
    61: "Hide",
    62: "Hide",
    63: "Hide",
    64: "Hide",
    65: "Hide",
    66: "Hide",
    67: "Hide",
    68: "Hide",
    69: "Hide",
    70: "Hide",
    71: "Hide",
    72: "Bludgeon",
    73: "Bludgeon",
    74: "Bludgeon",
    75: "Bludgeon",
    76: "Bludgeon",
    78: "Metal",
    77: "Metal",
    79: "Metal",
    80: "Metal",
    81: "Metal",
    82: "Metal",
    83: "Metal",
    84: "Metal",
    85: "Metal",
    86: "Metal",
    87: "Metal",
    88: "Metal",
    89: "Metal",
    90: "Metal",
    91: "Metal",
    92: "Metal",
    93: "Metal",
    94: "Metal",
    95: "Metal",
    96: "Metal",
    97: "Metal",
    98: "Metal",
    99: "Metal",
    100: "Metal",
    101: "Metal",
};