import {hash} from "starknet";

export const SELECTOR_KEYS ={
    StartGame: hash.getSelectorFromName("StartGame"),
    AdventurerUpgraded: hash.getSelectorFromName("AdventurerUpgraded"),
    DiscoveredHealth: hash.getSelectorFromName("DiscoveredHealth"),
    DiscoveredGold: hash.getSelectorFromName("DiscoveredGold"),
    DiscoveredXP: hash.getSelectorFromName("DiscoveredXP"),
    DodgedObstacle: hash.getSelectorFromName("DodgedObstacle"),
    HitByObstacle: hash.getSelectorFromName("HitByObstacle"),
    DiscoveredBeast: hash.getSelectorFromName("DiscoveredBeast"),
    AmbushedByBeast: hash.getSelectorFromName("AmbushedByBeast"),
    AttackedBeast: hash.getSelectorFromName("AttackedBeast"),
    AttackedByBeast: hash.getSelectorFromName("AttackedByBeast"),
    SlayedBeast: hash.getSelectorFromName("SlayedBeast"),
    FleeFailed: hash.getSelectorFromName("FleeFailed"),
    FleeSucceeded: hash.getSelectorFromName("FleeSucceeded"),
    PurchasedItems: hash.getSelectorFromName("PurchasedItems"),
    PurchasedPotions: hash.getSelectorFromName("PurchasedPotions"),
    EquippedItems: hash.getSelectorFromName("EquippedItems"),
    DroppedItems: hash.getSelectorFromName("DroppedItems"),
    GreatnessIncreased: hash.getSelectorFromName("GreatnessIncreased"),
    ItemsLeveledUp: hash.getSelectorFromName("ItemsLeveledUp"),
    NewHighScore: hash.getSelectorFromName("NewHighScore"),
    AdventurerDied: hash.getSelectorFromName("AdventurerDied"),
    AdventurerLeveledUp: hash.getSelectorFromName("AdventurerLeveledUp"),
    NewItemsAvailable: hash.getSelectorFromName("NewItemsAvailable"),
    IdleDeathPenalty: hash.getSelectorFromName("IdleDeathPenalty"),
    ResUpdate: hash.getSelectorFromName("ResUpdate"),
}


export const ITEMS = {
    1: "Pendant",
    2: "Necklace",
    3: "Amulet",
    4: "Silver Ring",
    5: "Bronze Ring",
    6: "Platinum Ring",
    7: "Titanium Ring",
    8: "Gold Ring",
    9: "Ghost Wand",
    10: "Grave Wand",
    11: "Bone Wand",
    12: "Wand",
    13: "Grimoire",
    14: "Chronicle",
    15: "Tome",
    16: "Book",
    17: "Divine Robe",
    18: "Silk Robe",
    19: "Linen Robe",
    20: "Robe",
    21: "Shirt",
    22: "Crown",
    23: "Divine Hood",
    24: "Silk Hood",
    25: "Linen Hood",
    26: "Hood",
    27: "Brightsilk Sash",
    28: "Silk Sash",
    29: "Wool Sash",
    30: "Linen Sash",
    31: "Sash",
    32: "Divine Slippers",
    33: "Silk Slippers",
    34: "Wool Shoes",
    35: "Linen Shoes",
    36: "Shoes",
    37: "Divine Gloves",
    38: "Silk Gloves",
    39: "Wool Gloves",
    40: "Linen Gloves",
    41: "Gloves",
    42: "Katana",
    43: "Falchion",
    44: "Scimitar",
    45: "Long Sword",
    46: "Short Sword",
    47: "Demon Husk",
    48: "Dragonskin Armor",
    49: "Studded Leather Armor",
    50: "Hard Leather Armor",
    51: "Leather Armor",
    52: "Demon Crown",
    53: "Dragons Crown",
    54: "War Cap",
    55: "Leather Cap",
    56: "Cap",
    57: "Demonhide Belt",
    58: "Dragonskin Belt",
    59: "Studded Leather Belt",
    60: "Hard Leather Belt",
    61: "Leather Belt",
    62: "Demonhide Boots",
    63: "Dragonskin Boots",
    64: "Studded Leather Boots",
    65: "Hard Leather Boots",
    66: "Leather Boots",
    67: "Demons Hands",
    68: "Dragonskin Gloves",
    69: "Studded Leather Gloves",
    70: "Hard Leather Gloves",
    71: "Leather Gloves",
    72: "Warhammer",
    73: "Quarterstaff",
    74: "Maul",
    75: "Mace",
    76: "Club",
    77: "Holy Chestplate",
    78: "Ornate Chestplate",
    79: "Plate Mail",
    80: "Chain Mail",
    81: "Ring Mail",
    82: "Ancient Helm",
    83: "Ornate Helm",
    84: "Great Helm",
    85: "Full Helm",
    86: "Helm",
    87: "Ornate Belt",
    88: "War Belt",
    89: "Plated Belt",
    90: "Mesh Belt",
    91: "Heavy Belt",
    92: "Holy Greaves",
    93: "Ornate Greaves",
    94: "Greaves",
    95: "Chain Boots",
    96: "Heavy Boots",
    97: "Holy Gauntlets",
    98: "Ornate Gauntlets",
    99: "Gauntlets",
    100: "Chain Gloves",
    101: "Heavy Gloves",
};

export const ITEM_TYPES = {
    1: "Necklace",
    2: "Necklace",
    3: "Necklace",
    4: "Ring",
    5: "Ring",
    6: "Ring",
    7: "Ring",
    8: "Ring",
    9: "Magic",
    10: "Magic",
    11: "Magic",
    12: "Magic",
    13: "Magic",
    14: "Magic",
    15: "Magic",
    16: "Magic",
    17: "Cloth",
    18: "Cloth",
    19: "Cloth",
    20: "Cloth",
    21: "Cloth",
    22: "Cloth",
    23: "Cloth",
    24: "Cloth",
    25: "Cloth",
    26: "Cloth",
    27: "Cloth",
    28: "Cloth",
    29: "Cloth",
    30: "Cloth",
    31: "Cloth",
    32: "Cloth",
    33: "Cloth",
    34: "Cloth",
    35: "Cloth",
    36: "Cloth",
    37: "Cloth",
    38: "Cloth",
    39: "Cloth",
    40: "Cloth",
    41: "Cloth",
    42: "Blade",
    43: "Blade",
    44: "Blade",
    45: "Blade",
    46: "Blade",
    47: "Hide",
    48: "Hide",
    49: "Hide",
    50: "Hide",
    51: "Hide",
    52: "Hide",
    53: "Hide",
    54: "Hide",
    55: "Hide",
    56: "Hide",
    57: "Hide",
    58: "Hide",
    59: "Hide",
    60: "Hide",
    61: "Hide",
    62: "Hide",
    63: "Hide",
    64: "Hide",
    65: "Hide",
    66: "Hide",
    67: "Hide",
    68: "Hide",
    69: "Hide",
    70: "Hide",
    71: "Hide",
    72: "Bludgeon",
    73: "Bludgeon",
    74: "Bludgeon",
    75: "Bludgeon",
    76: "Bludgeon",
    78: "Metal",
    77: "Metal",
    79: "Metal",
    80: "Metal",
    81: "Metal",
    82: "Metal",
    83: "Metal",
    84: "Metal",
    85: "Metal",
    86: "Metal",
    87: "Metal",
    88: "Metal",
    89: "Metal",
    90: "Metal",
    91: "Metal",
    92: "Metal",
    93: "Metal",
    94: "Metal",
    95: "Metal",
    96: "Metal",
    97: "Metal",
    98: "Metal",
    99: "Metal",
    100: "Metal",
    101: "Metal",
};

export const ITEM_TIERS = {
    Pendant: 1,
    Necklace: 1,
    Amulet: 1,
    SilverRing: 2,
    BronzeRing: 3,
    PlatinumRing: 1,
    TitaniumRing: 1,
    GoldRing: 1,
    GhostWand: 1,
    GraveWand: 2,
    BoneWand: 3,
    Wand: 5,
    Grimoire: 1,
    Chronicle: 2,
    Tome: 3,
    Book: 5,
    DivineRobe: 1,
    SilkRobe: 2,
    LinenRobe: 3,
    Robe: 4,
    Shirt: 5,
    Crown: 1,
    DivineHood: 2,
    SilkHood: 3,
    LinenHood: 4,
    Hood: 5,
    BrightsilkSash: 1,
    SilkSash: 2,
    WoolSash: 3,
    LinenSash: 4,
    Sash: 5,
    DivineSlippers: 1,
    SilkSlippers: 2,
    WoolShoes: 3,
    LinenShoes: 4,
    Shoes: 5,
    DivineGloves: 1,
    SilkGloves: 2,
    WoolGloves: 3,
    LinenGloves: 4,
    Gloves: 5,
    Katana: 1,
    Falchion: 2,
    Scimitar: 3,
    LongSword: 4,
    ShortSword: 5,
    DemonHusk: 1,
    DragonskinArmor: 2,
    StuddedLeatherArmor: 3,
    HardLeatherArmor: 4,
    LeatherArmor: 5,
    DemonCrown: 1,
    DragonsCrown: 2,
    WarCap: 3,
    LeatherCap: 4,
    Cap: 5,
    DemonhideBelt: 1,
    DragonskinBelt: 2,
    StuddedLeatherBelt: 3,
    HardLeatherBelt: 4,
    LeatherBelt: 5,
    DemonhideBoots: 1,
    DragonskinBoots: 2,
    StuddedLeatherBoots: 3,
    HardLeatherBoots: 4,
    LeatherBoots: 5,
    DemonsHands: 1,
    DragonskinGloves: 2,
    StuddedLeatherGloves: 3,
    HardLeatherGloves: 4,
    LeatherGloves: 5,
    Warhammer: 1,
    Quarterstaff: 2,
    Maul: 3,
    Mace: 4,
    Club: 5,
    HolyChestplate: 1,
    OrnateChestplate: 2,
    PlateMail: 3,
    ChainMail: 4,
    RingMail: 5,
    AncientHelm: 1,
    OrnateHelm: 2,
    GreatHelm: 3,
    FullHelm: 4,
    Helm: 5,
    OrnateBelt: 1,
    WarBelt: 2,
    PlatedBelt: 3,
    MeshBelt: 4,
    HeavyBelt: 5,
    HolyGreaves: 1,
    OrnateGreaves: 2,
    Greaves: 3,
    ChainBoots: 4,
    HeavyBoots: 5,
    HolyGauntlets: 1,
    OrnateGauntlets: 2,
    Gauntlets: 3,
    ChainGloves: 4,
    HeavyGloves: 5,
};

export const ITEM_SLOTS = {
    Pendant: "Neck",
    Necklace: "Neck",
    Amulet: "Neck",
    SilverRing: "Ring",
    BronzeRing: "Ring",
    PlatinumRing: "Ring",
    TitaniumRing: "Ring",
    GoldRing: "Ring",
    GhostWand: "Weapon",
    GraveWand: "Weapon",
    BoneWand: "Weapon",
    Wand: "Weapon",
    Grimoire: "Weapon",
    Chronicle: "Weapon",
    Tome: "Weapon",
    Book: "Weapon",
    DivineRobe: "Chest",
    SilkRobe: "Chest",
    LinenRobe: "Chest",
    Robe: "Chest",
    Shirt: "Chest",
    Crown: "Head",
    DivineHood: "Head",
    SilkHood: "Head",
    LinenHood: "Head",
    Hood: "Head",
    BrightsilkSash: "Waist",
    SilkSash: "Waist",
    WoolSash: "Waist",
    LinenSash: "Waist",
    Sash: "Waist",
    DivineSlippers: "Foot",
    SilkSlippers: "Foot",
    WoolShoes: "Foot",
    LinenShoes: "Foot",
    Shoes: "Foot",
    DivineGloves: "Hand",
    SilkGloves: "Hand",
    WoolGloves: "Hand",
    LinenGloves: "Hand",
    Gloves: "Hand",
    Katana: "Weapon",
    Falchion: "Weapon",
    Scimitar: "Weapon",
    LongSword: "Weapon",
    ShortSword: "Weapon",
    DemonHusk: "Chest",
    DragonskinArmor: "Chest",
    StuddedLeatherArmor: "Chest",
    HardLeatherArmor: "Chest",
    LeatherArmor: "Chest",
    DemonCrown: "Head",
    DragonsCrown: "Head",
    WarCap: "Head",
    LeatherCap: "Head",
    Cap: "Head",
    DemonhideBelt: "Waist",
    DragonskinBelt: "Waist",
    StuddedLeatherBelt: "Waist",
    HardLeatherBelt: "Waist",
    LeatherBelt: "Waist",
    DemonhideBoots: "Foot",
    DragonskinBoots: "Foot",
    StuddedLeatherBoots: "Foot",
    HardLeatherBoots: "Foot",
    LeatherBoots: "Foot",
    DemonsHands: "Hand",
    DragonskinGloves: "Hand",
    StuddedLeatherGloves: "Hand",
    HardLeatherGloves: "Hand",
    LeatherGloves: "Hand",
    Warhammer: "Weapon",
    Quarterstaff: "Weapon",
    Maul: "Weapon",
    Mace: "Weapon",
    Club: "Weapon",
    HolyChestplate: "Chest",
    OrnateChestplate: "Chest",
    PlateMail: "Chest",
    ChainMail: "Chest",
    RingMail: "Chest",
    AncientHelm: "Head",
    OrnateHelm: "Head",
    GreatHelm: "Head",
    FullHelm: "Head",
    Helm: "Head",
    OrnateBelt: "Waist",
    WarBelt: "Waist",
    PlatedBelt: "Waist",
    MeshBelt: "Waist",
    HeavyBelt: "Waist",
    HolyGreaves: "Foot",
    OrnateGreaves: "Foot",
    Greaves: "Foot",
    ChainBoots: "Foot",
    HeavyBoots: "Foot",
    HolyGauntlets: "Hand",
    OrnateGauntlets: "Hand",
    Gauntlets: "Hand",
    ChainGloves: "Hand",
    HeavyGloves: "Hand",
};